version: "3"
services:
  vue-web:
    build: .
    container_name: vue-container
    ports:
      - 3000:8080
    volumes:
      - .:/home/app
      - nodemodules:/home/app/node_modules

volumes:
  nodemodules: