version: 2

jobs: 
  build-app:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
        - run:
          name: Installing dependencies
          command: "npm install"
        - run:
          name: Building the project
          command: "npm run build"
        - persist_to_workspace:
          root: dist/
  app-deploy:
    docker:
      - image: circle/node:latest
    steps:
      - checkout
    - attach_workspace:
      at: dist/
    - run:
      name: Disable jekyll builds
      command: touch .nojekyll
    - run:
        name: Install and configure dependencies
        command: |
          npm install -g --silent gh-pages@2.0.1
          git config user.email "gegenbarcelos@gmail.com"
          git config user.name "gegen07"