version: 2

jobs: 
  "build-app":
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: dist/
          paths: .

  "app-deploy":
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: dist/
      - run:
          name: Disable jekyll builds
          command: touch .nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            git config --global user.email "gegenbarcelos@gmail.com"
            git config --global user.name "gegen07"
      - run:
          name: Avoid hosts unknown for github
          command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - add_ssh_keys:
          fingerprints:
            - "e4:cd:53:d5:40:fa:a6:8a:20:88:86:52:e6:fe:3d:f3"
      - run:
            name: Deploy docs to gh-pages branch
            command: |
              cd dist
              git init
              git checkout -b master
              git add -A
              git commit -m 'deploy'

              git push -f git@github.com:gegen07/gegen07.github.io.git master
workflows:
  version: 2
  build:
    jobs:
      - "build-app"
      - app-deploy:
          requires:
            - build-app 