version: 2

jobs: 
  "build-app":
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: dist/
          paths: .

  "app-deploy":
    docker:
      - image: circle/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: dist/
      - run:
        name: Disable jekyll builds
        command: touch .nojekyll
      - run:
        name: Install and configure dependencies
        command: |
          npm install -g --silent gh-pages@2.0.1
          git config user.email "gegenbarcelos@gmail.com"
          git config user.name "gegen07"
      - add_ssh_keys:
          fingerprints:
            - "e4:cd:53:d5:40:fa:a6:8a:20:88:86:52:e6:fe:3d:f3"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist dist/
workflows:
  version: 2
  build:
    jobs:
      - "build-app"
      - app-deploy:
          requires:
            - build-app
          filters:
            branches:
              only: master