version: 2

jobs: 
  "build-app":
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: dist/
          paths: .

  "app-deploy":
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: dist/
      - run:
          name: Disable jekyll builds
          command: touch .nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g --silent gh-pages@2.0.1
            git config user.email "gegenbarcelos@gmail.com"
            git config user.name "gegen07"
      - add_ssh_keys:
          fingerprints:
            - "ec:52:05:97:89:37:2c:89:f9:a7:55:53:9b:7d:3a:7a"
      - run:
            name: Deploy docs to gh-pages branch
            command: sudo gh-pages --dotfiles --message "[skip ci] Updates" --dist dist/
workflows:
  version: 2
  build:
    jobs:
      - "build-app"
      - app-deploy:
          requires:
            - build-app
          filters:
            branches:
              only: master